<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../WindowsSystemReadings.cs" Link="WindowsSystemReadings.cs" />
    <ProjectReference Include="../../../Core/Pulse.Core.csproj" />
    <ProjectReference Include="../../Common/Pulse.Adapters.Common.csproj" />
  </ItemGroup>
</Project>
